version: 2.1

jobs:
  sonarcloud:
    docker:
      - image: 'cimg/python:3.9.6'
    steps:
      - checkout
      - sonarcloud/scan
  semgrep-scan:
    parameters:
      default_branch:
        type: string
        default: main
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/ci
        p/typescript
        p/secrets
    docker:
      - image: returntocorp/semgrep-agent:v1
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep-agent
  snyk-scan:
    working_directory: ~/app
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run: 
          name: "npm-install"
          command: |
            npm init
            npm install sqlite3
            npm install -q
      - snyk/scan
  trufflehog-scan:
    docker:
      - image: 'cimg/python:3.9.6'
    steps:
      - checkout
      - run: pip3 install trufflehog
      - run: trufflehog --regex --entropy=False .      
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  snyk: snyk/snyk@1.0.2
workflows:
  main:
    jobs:
      - sonarcloud:
          context: SonarCloud
      - semgrep-scan
      - snyk-scan:
          context: SnykToken
      - trufflehog-scan
      # Supported file extensions for IaC are tf, yml, yaml & json    
      # - snyk/scan-iac:
      #     context: SnykToken

